version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mmdadmin
      MONGO_INITDB_ROOT_PASSWORD: mmdadmin123
      MONGO_INITDB_DATABASE: test
      DB_NAME: test
    ports:
      - 27017:27017
    volumes:
      - ./mongodump/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db/:/data/db
  server:
    restart: always
    build: ./server
    environment:
      MONGO_USERNAME: mmdadmin
      MONGO_PASSWORD: mmdadmin123
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DB: test
    ports:
      - 8080:8080
    volumes:
      - ./server/:/code
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
    stdin_open: true
  mongo-seed:
    build: ./mongodump/
    links:
      - mongodb
    depends_on:
      - mongodb
  mongo-assignment-seed:
    build: ./mongodump3/
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
 mongodb: