version: '3.8'
services:
  server:
    restart: always
    build: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server/:/code
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
    stdin_open: true